# Global configuration
global:
  scrape_interval: 5s       # How often Prometheus scrapes metrics from targets
  evaluation_interval: 5s   # How often Prometheus evaluates rules


alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]

rule_files: [ ]

# Scrape configurations for different targets
scrape_configs:

  # Prometheus' own metrics
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]   # Prometheus exposes its own metrics here


  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  # PostgreSQL metrics via Postgres Exporter
  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]   # Postgres Exporter container

  # MongoDB metrics via MongoDB Exporter
  - job_name: "mongodb"
    static_configs:
      - targets: [ "mongodb-exporter:9216" ]   # MongoDB Exporter container




