export * from './dashboard/DashboardPage';
export * from './products/ProductsPage';
export * from './cart/CartPage';
export * from './orders/OrdersPage';
export * from './customers/CustomersPage';
export * from './payments/PaymentsPage';
export * from './discounts/DiscountsPage';
export * from './stocks/StocksPage';
export * from './settings/SettingsPage';
